[options]
addons_path = D:\odoo19CE\odoo19CE\addons,D:\odoo19CE\odoo19CE\odoo\addons,D:\odoo19CE\odoo19ee-addons\odoo19ee-addons,D:\custom_module\file\addon
db_user = odoo19
db_password = odoo19
default_productivity_apps = True
db_host = localhost
db_port = 5432
dbfilter = 
gevent_port = 8072
http_enable = True
http_interface = 
http_port = 8800
list_db = True
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = 
workers = 0
admin_passwd = $pbkdf2-sha512$600000$D4EQ4vwfA.D8H6OU8h4DgA$Mps/avjOuKpydlxkTHr64hcttYWEwa72XNIF0iEyVOe/vDk10lcfy01ZJhvdcwF/1GHIJR591emreSkqv1wMNw

